# Generated by Django 5.2.5 on 2025-09-08 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('wallet_address', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('is_excluded_from_tracking', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_streak', models.IntegerField(default=0)),
                ('total_earnings', models.DecimalField(decimal_places=6, max_digits=20)),
            ],
            options={
                'db_table': 'accounts_account',
            },
        ),
    ]
