# Generated by Django 5.2.5 on 2025-09-08 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculated_balance', models.DecimalField(decimal_places=6, max_digits=20)),
                ('actual_balance', models.DecimalField(decimal_places=6, max_digits=20)),
                ('discrepancy', models.DecimalField(decimal_places=6, max_digits=20)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
            options={
                'db_table': 'wallet_monitoring_balancelog',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='ManualTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=6, max_digits=20)),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Manual Deposit'), ('WITHDRAWAL', 'Manual Withdrawal')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
            options={
                'db_table': 'wallet_monitoring_manualtransaction',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
