# Generated by Django 5.2.5 on 2025-09-08 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_provider', models.CharField(max_length=50)),
                ('last_checked', models.DateTimeField()),
                ('credentials_encrypted', models.TextField()),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
            options={
                'db_table': 'email_monitoring_emailaccount',
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField()),
                ('sender', models.EmailField(max_length=254)),
                ('receiver', models.EmailField(max_length=254)),
                ('forwarded_from', models.EmailField(blank=True, max_length=254, null=True)),
                ('content_hash', models.CharField(max_length=64)),
                ('raw_headers', models.JSONField()),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
            options={
                'db_table': 'email_monitoring_emaillog',
                'unique_together': {('account', 'content_hash')},
            },
        ),
        migrations.CreateModel(
            name='SubmissionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SELECTED_NOT_DRAWN', 'Selected but not drawn'), ('DRAWN_WON', 'Drawn and won'), ('REJECTED', 'Rejected'), ('STREAK_PAYOUT', 'Streak payout')], max_length=20)),
                ('amount', models.IntegerField(blank=True, choices=[(10, '10 STX'), (15, '15 STX'), (30, '30 STX'), (100, '100 STX'), (200, '200 STX'), (500, '500 STX'), (2500, '2500 STX')], null=True)),
                ('submission_date', models.DateTimeField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('email_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email_monitoring.emaillog')),
            ],
            options={
                'db_table': 'email_monitoring_submissionstatus',
            },
        ),
    ]
