# Generated by Django 5.2.5 on 2025-09-08 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('BALANCE_DISCREPANCY', 'Balance Discrepancy'), ('SUBMISSION_REJECTED', 'Submisson Rejected'), ('RAFFLE_WON', 'Raffle Won'), ('STREAK_BROKEN', 'Streak Broken'), ('STREAK_PAYOUT', 'Streak Payout')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('threshold_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'notifications_notificationrule',
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('SUCCESS', 'Success')], max_length=10)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.notificationrule')),
            ],
            options={
                'db_table': 'notifications_alert',
                'ordering': ['-created_at'],
            },
        ),
    ]
